//
// Autogenerated by Natalie - Storyboard Generator Script.
// http://blog.krzyzanowskim.com
//

import UIKit

//MARK: - Storyboards

extension UIStoryboard {
    func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
        let instance = type.init()
        if let identifier = instance.storyboardIdentifier {
            return self.instantiateViewControllerWithIdentifier(identifier) as? T
        }
        return nil
    }

}

protocol Storyboard {
    static var storyboard: UIStoryboard { get }
    static var identifier: String { get }
}

struct Storyboards {

    struct LaunchScreen: Storyboard {

        static let identifier = "LaunchScreen"

        static var storyboard: UIStoryboard {
            return UIStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateInitialViewController() -> UIViewController {
            return self.storyboard.instantiateInitialViewController()!
        }

        static func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier(identifier)
        }

        static func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
            return self.storyboard.instantiateViewController(type)
        }
    }

    struct Main: Storyboard {

        static let identifier = "Main"

        static var storyboard: UIStoryboard {
            return UIStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateInitialViewController() -> UINavigationController {
            return self.storyboard.instantiateInitialViewController() as! UINavigationController
        }

        static func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier(identifier)
        }

        static func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
            return self.storyboard.instantiateViewController(type)
        }

        static func instantiateMainViewController() -> MainViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("MainViewController") as! MainViewController
        }

        static func instantiateCharactersTableViewController() -> CharactersTableViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CharactersTableViewController") as! CharactersTableViewController
        }

        static func instantiateCharacterDetailViewController() -> CharacterDetailViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CharacterDetailViewController") as! CharacterDetailViewController
        }

        static func instantiateItemsTableViewController() -> ItemsTableViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("ItemsTableViewController") as! ItemsTableViewController
        }

        static func instantiateResourcesCollectionViewController() -> ResourcesCollectionViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("ResourcesCollectionViewController") as! ResourcesCollectionViewController
        }
    }
}

//MARK: - ReusableKind
enum ReusableKind: String, CustomStringConvertible {
    case TableViewCell = "tableViewCell"
    case CollectionViewCell = "collectionViewCell"

    var description: String { return self.rawValue }
}

//MARK: - SegueKind
enum SegueKind: String, CustomStringConvertible {    
    case Relationship = "relationship" 
    case Show = "show"                 
    case Presentation = "presentation" 
    case Embed = "embed"               
    case Unwind = "unwind"             
    case Push = "push"                 
    case Modal = "modal"               
    case Popover = "popover"           
    case Replace = "replace"           
    case Custom = "custom"             

    var description: String { return self.rawValue } 
}

//MARK: - IdentifiableProtocol

public protocol IdentifiableProtocol: Equatable {
    var storyboardIdentifier: String? { get }
}

//MARK: - SegueProtocol

public protocol SegueProtocol {
    var identifier: String? { get }
}

public func ==<T: SegueProtocol, U: SegueProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

public func ~=<T: SegueProtocol, U: SegueProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

public func ==<T: SegueProtocol>(lhs: T, rhs: String) -> Bool {
    return lhs.identifier == rhs
}

public func ~=<T: SegueProtocol>(lhs: T, rhs: String) -> Bool {
    return lhs.identifier == rhs
}

public func ==<T: SegueProtocol>(lhs: String, rhs: T) -> Bool {
    return lhs == rhs.identifier
}

public func ~=<T: SegueProtocol>(lhs: String, rhs: T) -> Bool {
    return lhs == rhs.identifier
}

//MARK: - ReusableViewProtocol
public protocol ReusableViewProtocol: IdentifiableProtocol {
    var viewType: UIView.Type? { get }
}

public func ==<T: ReusableViewProtocol, U: ReusableViewProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.storyboardIdentifier == rhs.storyboardIdentifier
}

//MARK: - Protocol Implementation
extension UIStoryboardSegue: SegueProtocol {
}

extension UICollectionReusableView: ReusableViewProtocol {
    public var viewType: UIView.Type? { return self.dynamicType }
    public var storyboardIdentifier: String? { return self.reuseIdentifier }
}

extension UITableViewCell: ReusableViewProtocol {
    public var viewType: UIView.Type? { return self.dynamicType }
    public var storyboardIdentifier: String? { return self.reuseIdentifier }
}

//MARK: - UIViewController extension
extension UIViewController {
    func performSegue<T: SegueProtocol>(segue: T, sender: AnyObject?) {
        if let identifier = segue.identifier {
            performSegueWithIdentifier(identifier, sender: sender)
        }
    }

    func performSegue<T: SegueProtocol>(segue: T) {
        performSegue(segue, sender: nil)
    }
}

//MARK: - UICollectionView

extension UICollectionView {

    func dequeueReusableCell<T: ReusableViewProtocol>(reusable: T, forIndexPath: NSIndexPath!) -> UICollectionViewCell? {
        if let identifier = reusable.storyboardIdentifier {
            return dequeueReusableCellWithReuseIdentifier(identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusableCell<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.storyboardIdentifier {
            registerClass(type, forCellWithReuseIdentifier: identifier)
        }
    }

    func dequeueReusableSupplementaryViewOfKind<T: ReusableViewProtocol>(elementKind: String, withReusable reusable: T, forIndexPath: NSIndexPath!) -> UICollectionReusableView? {
        if let identifier = reusable.storyboardIdentifier {
            return dequeueReusableSupplementaryViewOfKind(elementKind, withReuseIdentifier: identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusable<T: ReusableViewProtocol>(reusable: T, forSupplementaryViewOfKind elementKind: String) {
        if let type = reusable.viewType, identifier = reusable.storyboardIdentifier {
            registerClass(type, forSupplementaryViewOfKind: elementKind, withReuseIdentifier: identifier)
        }
    }
}
//MARK: - UITableView

extension UITableView {

    func dequeueReusableCell<T: ReusableViewProtocol>(reusable: T, forIndexPath: NSIndexPath!) -> UITableViewCell? {
        if let identifier = reusable.storyboardIdentifier {
            return dequeueReusableCellWithIdentifier(identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusableCell<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.storyboardIdentifier {
            registerClass(type, forCellReuseIdentifier: identifier)
        }
    }

    func dequeueReusableHeaderFooter<T: ReusableViewProtocol>(reusable: T) -> UITableViewHeaderFooterView? {
        if let identifier = reusable.storyboardIdentifier {
            return dequeueReusableHeaderFooterViewWithIdentifier(identifier)
        }
        return nil
    }

    func registerReusableHeaderFooter<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.storyboardIdentifier {
             registerClass(type, forHeaderFooterViewReuseIdentifier: identifier)
        }
    }
}


//MARK: - MainViewController
extension UIStoryboardSegue {
    func selection() -> MainViewController.Segue? {
        if let identifier = self.identifier {
            return MainViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension MainViewController: IdentifiableProtocol { 
    var storyboardIdentifier: String? { return "MainViewController" }
    static var storyboardIdentifier: String? { return "MainViewController" }
}

extension MainViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case embededCharactersListInMainView = "embededCharactersListInMainView"

        var kind: SegueKind? {
            switch (self) {
            case embededCharactersListInMainView:
                return SegueKind(rawValue: "embed")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case embededCharactersListInMainView:
                return CharactersTableViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - CharactersTableViewController
extension UIStoryboardSegue {
    func selection() -> CharactersTableViewController.Segue? {
        if let identifier = self.identifier {
            return CharactersTableViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension CharactersTableViewController: IdentifiableProtocol { 
    var storyboardIdentifier: String? { return "CharactersTableViewController" }
    static var storyboardIdentifier: String? { return "CharactersTableViewController" }
}

extension CharactersTableViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case fromCharactersListToCharacterDetail = "fromCharactersListToCharacterDetail"

        var kind: SegueKind? {
            switch (self) {
            case fromCharactersListToCharacterDetail:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case fromCharactersListToCharacterDetail:
                return CharacterDetailViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}
extension CharactersTableViewController { 

    enum Reusable: String, CustomStringConvertible, ReusableViewProtocol {
        case CharacterTableViewCell_ = "CharacterTableViewCell"

        var kind: ReusableKind? {
            switch (self) {
            case CharacterTableViewCell_:
                return ReusableKind(rawValue: "tableViewCell")
            }
        }

        var viewType: UIView.Type? {
            switch (self) {
            case CharacterTableViewCell_:
                return CharacterTableViewCell.self
            }
        }

        var storyboardIdentifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}


//MARK: - CharacterDetailViewController
extension UIStoryboardSegue {
    func selection() -> CharacterDetailViewController.Segue? {
        if let identifier = self.identifier {
            return CharacterDetailViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension CharacterDetailViewController: IdentifiableProtocol { 
    var storyboardIdentifier: String? { return "CharacterDetailViewController" }
    static var storyboardIdentifier: String? { return "CharacterDetailViewController" }
}

extension CharacterDetailViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case embededItemsListInCharacterDetail = "embededItemsListInCharacterDetail"

        var kind: SegueKind? {
            switch (self) {
            case embededItemsListInCharacterDetail:
                return SegueKind(rawValue: "embed")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case embededItemsListInCharacterDetail:
                return ItemsTableViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - ItemsTableViewController
extension ItemsTableViewController: IdentifiableProtocol { 
    var storyboardIdentifier: String? { return "ItemsTableViewController" }
    static var storyboardIdentifier: String? { return "ItemsTableViewController" }
}

extension ItemsTableViewController { 

    enum Reusable: String, CustomStringConvertible, ReusableViewProtocol {
        case ItemTableViewCell_ = "ItemTableViewCell"

        var kind: ReusableKind? {
            switch (self) {
            case ItemTableViewCell_:
                return ReusableKind(rawValue: "tableViewCell")
            }
        }

        var viewType: UIView.Type? {
            switch (self) {
            case ItemTableViewCell_:
                return ItemTableViewCell.self
            }
        }

        var storyboardIdentifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}


//MARK: - ResourcesCollectionViewController
extension ResourcesCollectionViewController: IdentifiableProtocol { 
    var storyboardIdentifier: String? { return "ResourcesCollectionViewController" }
    static var storyboardIdentifier: String? { return "ResourcesCollectionViewController" }
}

extension ResourcesCollectionViewController { 

    enum Reusable: String, CustomStringConvertible, ReusableViewProtocol {
        case ResourceCollectionViewCell_ = "ResourceCollectionViewCell"

        var kind: ReusableKind? {
            switch (self) {
            case ResourceCollectionViewCell_:
                return ReusableKind(rawValue: "collectionViewCell")
            }
        }

        var viewType: UIView.Type? {
            switch (self) {
            case ResourceCollectionViewCell_:
                return ResourceCollectionViewCell.self
            }
        }

        var storyboardIdentifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

